apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pod-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
